from typing import Optional, List, Dict
from pydantic import BaseModel, Field, validator
from datetime import datetime

# -------------------------------------
# Robot Status Enum
# -------------------------------------
ROBOT_STATUSES = {"IDLE", "BUSY", "ERROR", "OFFLINE"}


# =========================================================
# PRODUCT MODELS
# =========================================================
class ProductCreate(BaseModel):
    name: str = Field(..., min_length=1, max_length=200)
    sku: str = Field(..., min_length=1, max_length=100)
    quantity: int = Field(ge=0)

    category: Optional[str] = Field(default=None, max_length=100)
    brand: Optional[str] = Field(default=None, max_length=100)
    price: Optional[float] = Field(default=None, ge=0)
    weight_kg: Optional[float] = Field(default=None, ge=0)
    dimensions_cm: Optional[Dict[str, float]] = None
    barcode: Optional[str] = Field(default=None, max_length=100)

    main_image_url: Optional[str] = None
    image_urls: List[str] = Field(default_factory=list)
    shelf_id: Optional[str] = None
    description: Optional[str] = Field(default=None, max_length=1000)

    @validator("*", pre=True)
    def strip_all(cls, v):
        return v.strip() if isinstance(v, str) else v


class ProductUpdate(BaseModel):
    name: Optional[str] = Field(default=None, min_length=1, max_length=200)
    sku: Optional[str] = Field(default=None, min_length=1, max_length=100)
    quantity: Optional[int] = Field(default=None, ge=0)
    category: Optional[str] = None
    brand: Optional[str] = None
    price: Optional[float] = Field(default=None, ge=0)
    weight_kg: Optional[float] = Field(default=None, ge=0)
    dimensions_cm: Optional[Dict[str, float]] = None
    barcode: Optional[str] = None
    main_image_url: Optional[str] = None
    image_urls: Optional[List[str]] = None
    shelf_id: Optional[str] = None
    description: Optional[str] = Field(default=None, max_length=1000)


# =========================================================
# SHELF MODELS
# =========================================================
class ShelfCreate(BaseModel):
    """
    Shelf creation model

    - current_*  : current live position on the map
    - storage_*  : immutable home/reference position (used for RETURN)
    """

    warehouse_id: str = Field(..., min_length=1, max_length=100)

    # -----------------------------
    # CURRENT (LIVE) LOCATION
    # -----------------------------
    current_x: float = Field(..., description="Current X position on map")
    current_y: float = Field(..., description="Current Y position on map")
    current_yaw: Optional[float] = Field(default=0.0)

    level: int = Field(..., ge=0)

    # -----------------------------
    # STORAGE (HOME) LOCATION
    # -----------------------------
    storage_x: Optional[float] = Field(
        default=None,
        description="Storage/home X (if None, backend copies from current_x)"
    )
    storage_y: Optional[float] = Field(
        default=None,
        description="Storage/home Y (if None, backend copies from current_y)"
    )
    storage_yaw: Optional[float] = Field(
        default=0.0,
        description="Storage/home yaw"
    )

    # -----------------------------
    # STATE
    # -----------------------------
    available: bool = True
    status: str = Field(default="IDLE")  # IDLE | BUSY | ERROR | OFFLINE

    # AprilTag (generated by backend)
    april_tag_url: Optional[str] = None

    @validator("warehouse_id", "status", pre=True)
    def strip_strings(cls, v):
        return v.strip() if isinstance(v, str) else v


class ShelfUpdate(BaseModel):
    """
    Shelf update model

    - current_* updates happen automatically by robot movement
    - storage_* updates allowed ONLY for admin/manual correction
    """

    warehouse_id: Optional[str] = Field(default=None, min_length=1, max_length=100)

    # -----------------------------
    # CURRENT LOCATION (LIVE)
    # -----------------------------
    current_x: Optional[float] = None
    current_y: Optional[float] = None
    current_yaw: Optional[float] = None

    level: Optional[int] = Field(default=None, ge=0)

    # -----------------------------
    # STORAGE LOCATION (RARE UPDATE)
    # -----------------------------
    storage_x: Optional[float] = None
    storage_y: Optional[float] = None
    storage_yaw: Optional[float] = None

    # -----------------------------
    # STATE
    # -----------------------------
    available: Optional[bool] = None
    status: Optional[str] = None

    # Optional tracking field
    location_status: Optional[str] = Field(
        default=None,
        description="AT_STORAGE | AT_ZONE | IN_TRANSIT"
    )

    april_tag_url: Optional[str] = None

    @validator(
        "warehouse_id",
        "status",
        "location_status",
        "april_tag_url",
        pre=True
    )
    def strip_strings(cls, v):
        return v.strip() if isinstance(v, str) else None


# =========================================================
# ROBOT MODELS
# =========================================================
class RobotCreate(BaseModel):
    """
    Robot creation model.
    
    Uses STATUS field for robot state:
    - IDLE: Ready for tasks (default)
    - BUSY: Currently executing a task
    - ERROR: Needs attention/maintenance
    - OFFLINE: Not connected
    
    The 'available' field is DEPRECATED and ignored in backend logic.
    """
    name: str
    robot_id: str
    status: str = "IDLE"  # IDLE | BUSY | ERROR | OFFLINE
    current_shelf_id: Optional[str] = None
    
    # Robot position tracking
    current_x: Optional[float] = None
    current_y: Optional[float] = None
    current_yaw: Optional[float] = 0.0
    
    # DEPRECATED: Kept for backward compatibility only, ignored in logic
    # Use 'status' field instead: IDLE = available, BUSY = unavailable
    available: Optional[bool] = None

    @validator("status")
    def validate_status(cls, v):
        v = v.strip().upper()
        if v not in ROBOT_STATUSES:
            raise ValueError(f"status must be one of {ROBOT_STATUSES}")
        return v

    @validator("name", "robot_id")
    def strip_text(cls, v):
        return v.strip()


class RobotUpdate(BaseModel):
    """
    Robot update model.
    
    Uses STATUS field for robot state:
    - IDLE: Ready for tasks
    - BUSY: Currently executing a task
    - ERROR: Needs attention/maintenance
    - OFFLINE: Not connected
    
    The 'available' field is DEPRECATED and ignored in backend logic.
    """
    name: Optional[str] = None
    robot_id: Optional[str] = None
    status: Optional[str] = None  # IDLE | BUSY | ERROR | OFFLINE
    current_shelf_id: Optional[str] = None
    
    # Robot position tracking
    current_x: Optional[float] = None
    current_y: Optional[float] = None
    current_yaw: Optional[float] = None
    
    # DEPRECATED: Kept for backward compatibility only, ignored in logic
    # Use 'status' field instead: IDLE = available, BUSY = unavailable
    available: Optional[bool] = None

    @validator("status")
    def validate_status(cls, v):
        if v is None:
            return v
        v = v.strip().upper()
        if v not in ROBOT_STATUSES:
            raise ValueError(f"status must be one of {ROBOT_STATUSES}")
        return v


# =========================================================
# ROBOT TELEMETRY (USED WITH INFLUXDB)
# =========================================================
class RobotTelemetry(BaseModel):
    """
    Robot telemetry data for InfluxDB.
    Includes position, battery, system metrics, and status.
    """
    cpu_usage: float = Field(..., ge=0, le=100)
    ram_usage: float = Field(..., ge=0, le=100)
    battery_level: float = Field(..., ge=0, le=100)
    temperature: float = Field(..., ge=-40, le=120)
    x: float
    y: float
    yaw: Optional[float] = 0.0  # Robot orientation in radians
    status: Optional[str] = None  # IDLE | BUSY | ERROR | OFFLINE

    timestamp: datetime = Field(default_factory=datetime.utcnow)

    @validator("status")
    def validate_status(cls, v):
        if v is None:
            return v
        v = v.strip().upper()
        if v not in ROBOT_STATUSES:
            raise ValueError(f"status must be one of {ROBOT_STATUSES}")
        return v


# =========================================================
# AUTH MODELS
# =========================================================
class AdminCreate(BaseModel):
    username: str = Field(..., min_length=3, max_length=50)
    password: str = Field(..., min_length=6, max_length=128)

    @validator("username")
    def strip_username(cls, v):
        return v.strip()


class AdminLogin(BaseModel):
    username: str
    password: str

    @validator("username")
    def strip_username(cls, v):
        return v.strip()


# =========================================================
# TASK MODELS
# =========================================================
class TaskCreate(BaseModel):
    """
    Task creation model.
    
    task_type values:
    - PICKUP_AND_DELIVER: Pick shelf from current location, deliver to zone
    - MOVE_SHELF: Move shelf to target_shelf_id location
    - RETURN_SHELF: Return shelf from zone back to storage location
    - REPOSITION: Reposition shelf to target_zone_id
    """
    shelf_id: str
    priority: int = Field(default=1, ge=1, le=10)
    description: Optional[str] = None
    zone_id: Optional[str] = None
    task_type: str = Field(default="PICKUP_AND_DELIVER")
    
    # For MOVE_SHELF: destination shelf/location
    target_shelf_id: Optional[str] = None
    
    # For REPOSITION: destination zone
    target_zone_id: Optional[str] = None
    
    # Optional: origin/storage snapshots (populated by backend at creation time)
    origin_storage_x: Optional[float] = None
    origin_storage_y: Optional[float] = None
    origin_storage_yaw: Optional[float] = None
    origin_pickup_x: Optional[float] = None
    origin_pickup_y: Optional[float] = None
    origin_pickup_yaw: Optional[float] = None


class TaskStatusEnum(str):
    """
    Task status tracking with complete state machine.
    
    Status flow:
    PENDING → ASSIGNED → MOVING_TO_PICKUP → ARRIVED_AT_PICKUP → 
    ATTACHED → MOVING_TO_DROP → ARRIVED_AT_DROP → RELEASED → 
    MOVING_TO_REFERENCE → COMPLETED
    
    Error states: ERROR, CANCELLED
    """
    PENDING = "PENDING"
    ASSIGNED = "ASSIGNED"
    MOVING_TO_PICKUP = "MOVING_TO_PICKUP"
    ARRIVED_AT_PICKUP = "ARRIVED_AT_PICKUP"
    ATTACHED = "ATTACHED"
    MOVING_TO_DROP = "MOVING_TO_DROP"
    ARRIVED_AT_DROP = "ARRIVED_AT_DROP"
    RELEASED = "RELEASED"
    MOVING_TO_REFERENCE = "MOVING_TO_REFERENCE"
    COMPLETED = "COMPLETED"
    ERROR = "ERROR"
    CANCELLED = "CANCELLED"


# =========================================================
# ZONE MODELS
# =========================================================
class ZoneCreate(BaseModel):
    """Zone creation model for drop-off locations."""
    zone_id: str = Field(..., min_length=1, max_length=100)
    name: Optional[str] = Field(default=None, max_length=200)
    x: float
    y: float
    yaw: Optional[float] = 0.0

    @validator("zone_id", "name", pre=True)
    def strip_strings(cls, v):
        return v.strip() if isinstance(v, str) else v


class ZoneUpdate(BaseModel):
    """Zone update model."""
    name: Optional[str] = Field(default=None, max_length=200)
    x: Optional[float] = None
    y: Optional[float] = None
    yaw: Optional[float] = None

    @validator("name", pre=True)
    def strip_name(cls, v):
        return v.strip() if isinstance(v, str) else v


# =========================================================
# STOCK MODELS
# =========================================================
class ProductTransactionCreate(BaseModel):
    """Product stock transaction model."""
    product_id: str
    quantity: int = Field(..., gt=0)
    action: str = Field(..., pattern="^(PICK|RETURN|ADJUST)$")
    description: Optional[str] = None


class StockReturn(BaseModel):
    """Stock return model."""
    product_id: str
    quantity: int = Field(..., gt=0)
    description: Optional[str] = None


class StockAdjust(BaseModel):
    """Stock adjustment model."""
    product_id: str
    new_quantity: int = Field(..., ge=0)
    reason: Optional[str] = None


# =========================================================
# IMAGE MODELS
# =========================================================
class SetMainImage(BaseModel):
    """Set main product image."""
    image_url: str


class DeleteImage(BaseModel):
    """Delete product image by index."""
    index: int = Field(..., ge=0)